#!/usr/bin/env ruby

# usage: ruby assemble testcode.s > a.out
require 'optparse'
$params = ARGV.getopts('ad')
require "#{File.dirname(__FILE__)}/assembler"
as = Assembler.new
print as.run(ARGV[0])
