#!/usr/bin/env ruby

# usage: ruby assemble testcode.s lib.s > a.out
require 'optparse'
opt = OptionParser.new
opt.on('-a', '--ascii', 'prints the output in the form of ascii') {
  |v| $a_mode = v
}
opt.on('-d', '--debug', 'prints debug information') {
  |v| $d_mode =  v
}
opt.on('-x', '--hex', 'prints the output in the form of hexadecimal') {
  |v| $x_mode = v
}

require "#{File.dirname(__FILE__)}/assembler"
opt.parse!(ARGV)
as = Assembler.new
print as.run(ARGV)
