#!/usr/bin/env ruby

# usage: ruby assemble testcode.s > a.out
$dbg = 0
if ARGV[1] == '-d'
  $dbg = 1
end
require "#{File.dirname(__FILE__)}/assembler"
as = Assembler.new
print as.run(ARGV[0]) 
